language = "C"
header = "/* NactionsKit Blockchain Core - C Interface */"
include_guard = "NACTIONS_BLOCKCHAIN_CORE_H"
style = "tag"
cpp_compat = true

[parse]
parse_deps = true
include = ["nactions_blockchain_core"]

[export]
prefix = "NBC_"